import { describe, expect, it } from 'vitest';
import { Cipher } from '../src/crypto/aes.js';
import { csvCell, detectDelimiter, parseCsv } from '../src/import/csv.js';
import { detectDateFormat, parseLibreViewCsv } from '../src/import/libreview-csv.js';
import { loadEnv, MIN_POLL_SECONDS } from '../src/config/env.js';
import { backoffDelayMs, jitterMs } from '../src/collector/backoff.js';
import { dropNearDuplicates } from '../src/collector/store.js';
import { maskEmail } from '../src/routes/llu-accounts.js';

const KEY = Buffer.alloc(32, 1).toString('base64');

describe('Cipher (AES-256-GCM)', () => {
  it('şifreler/çözer, biçim v1:iv:tag:ct, her seferinde farklı IV', () => {
    const c = new Cipher(KEY);
    const a = c.encrypt('gizli@example.com');
    const b = c.encrypt('gizli@example.com');
    expect(a).toMatch(/^v1:[^:]+:[^:]+:[^:]+$/);
    expect(a).not.toBe(b);
    expect(c.decrypt(a)).toBe('gizli@example.com');
  });
  it('kurcalanmış veri reddedilir; yanlış anahtar; eski sürüm anahtarı', () => {
    const c = new Cipher(KEY);
    const enc = c.encrypt('x');
    const parts = enc.split(':');
    parts[3] = Buffer.from('y').toString('base64');
    expect(() => c.decrypt(parts.join(':'))).toThrow();
    expect(() => new Cipher(Buffer.alloc(32, 2).toString('base64')).decrypt(enc)).toThrow();
    expect(() => c.decrypt('v9:a:b:c')).toThrow();
    expect(() => new Cipher(Buffer.alloc(16).toString('base64'))).toThrow();
    const rotated = new Cipher(Buffer.alloc(32, 3).toString('base64'), { v0: KEY });
    expect(rotated.decrypt(enc.replace(/^v1/, 'v0'))).toBe('x');
  });
});

describe('env', () => {
  const base = {
    DATABASE_URL: 'postgresql://x',
    ENCRYPTION_KEY: KEY,
    SESSION_SECRET: 'x'.repeat(32),
  };
  it('polling 60 sn altına inemez', () => {
    expect(loadEnv({ ...base, LLU_POLL_SECONDS: '10' }).LLU_POLL_SECONDS).toBe(MIN_POLL_SECONDS);
    expect(loadEnv({ ...base, LLU_POLL_SECONDS: '120' }).LLU_POLL_SECONDS).toBe(120);
  });
  it('eksik/yanlış değerlerde açık hata', () => {
    expect(() => loadEnv({ ...base, ENCRYPTION_KEY: 'kısa' })).toThrow(/ENCRYPTION_KEY/);
    expect(() => loadEnv({ ENCRYPTION_KEY: KEY, SESSION_SECRET: 'x'.repeat(32) })).toThrow(
      /DATABASE_URL/,
    );
    expect(loadEnv({ ...base, LLU_MOCK: 'true' }).LLU_MOCK).toBe(true);
  });
});

describe('backoff / jitter / yakın kopya / maske', () => {
  it('1 → 2 → 4 … en fazla 30 dk', () => {
    expect([0, 1, 2, 3, 5, 6, 10].map((s) => backoffDelayMs(s) / 60_000)).toEqual([
      0, 1, 2, 4, 16, 30, 30,
    ]);
    expect(jitterMs(5000, () => 0)).toBe(-5000);
    expect(jitterMs(5000, () => 1)).toBe(5000);
  });
  it('±30 sn içinde aynı değer atlanır', () => {
    const t = Date.UTC(2026, 0, 1);
    const existing = [{ ts: new Date(t), mgdl: 100 }];
    const out = dropNearDuplicates(
      [
        { ts: new Date(t + 20_000), mgdl: 100 }, // yakın kopya
        { ts: new Date(t + 20_000 + 1), mgdl: 101 }, // farklı değer
        { ts: new Date(t), mgdl: 100 }, // aynı ts → upsert'e bırakılır
        { ts: new Date(t + 60_000), mgdl: 100 },
      ],
      existing,
    );
    expect(out.map((r) => r.ts.getTime() - t)).toEqual([20_001, 0, 60_000]);
  });
  it('e-posta maskeleme', () => {
    expect(maskEmail('ali@gmail.com')).toBe('a***@g***.com');
    expect(maskEmail('x@localhost')).toBe('x***@l***');
  });
});

describe('CSV', () => {
  it('tırnaklı alanlar ve satır sonları', () => {
    expect(parseCsv('a,"b,c","d""e"\r\n1,"x\ny",3', ',')).toEqual([
      ['a', 'b,c', 'd"e'],
      ['1', 'x\ny', '3'],
    ]);
    expect(detectDelimiter('a;b;c')).toBe(';');
  });
  it('dışa aktarma hücresi: enjeksiyon ve kaçış', () => {
    expect(csvCell('=HYPERLINK("x")')).toBe(`"'=HYPERLINK(""x"")"`);
    expect(csvCell('a;b')).toBe('"a;b"');
    expect(csvCell(-5)).toBe('-5');
    expect(csvCell(null)).toBe('');
  });
});

describe('LibreView CSV içe aktarma', () => {
  const en = [
    'Glucose Data,Generated on,09-27-2026 10:00 UTC,Generated by,Someone',
    'Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Notes',
    'FreeStyle LibreLink,ABC,09-25-2026 08:00,0,112,,',
    'FreeStyle LibreLink,ABC,09-25-2026 08:15,0,118,,',
    'FreeStyle LibreLink,ABC,09-25-2026 08:17,1,,121,"not, virgüllü"',
    'FreeStyle LibreLink,ABC,09-25-2026 08:20,6,,,',
    'FreeStyle LibreLink,ABC,09-25-2026 08:30,0,,,',
  ].join('\n');

  it('İngilizce başlık, ABD tarih biçimi, yerel saat → UTC', () => {
    const r = parseLibreViewCsv(en, 'Europe/Istanbul');
    expect(r.rows).toBe(5);
    expect(r.readings.map((x) => [x.ts.toISOString(), x.mgdl])).toEqual([
      ['2026-09-25T05:00:00.000Z', 112],
      ['2026-09-25T05:15:00.000Z', 118],
      ['2026-09-25T05:17:00.000Z', 121],
    ]);
    expect(r.skipped).toBe(2);
  });

  it('Türkçe başlık, ; ayırıcı, GG-AA-YYYY ve mmol/L', () => {
    const tr = [
      'Glukoz Verileri;Oluşturulma;27-09-2026',
      'Cihaz;Seri Numarası;Cihaz Zaman Damgası;Kayıt Türü;Geçmiş Glukoz mmol/L;Tarama Glukozu mmol/L',
      'FreeStyle LibreLink;ABC;25-09-2026 23:45;0;6,2;',
      'FreeStyle LibreLink;ABC;26-09-2026 00:00;0;6,0;',
      '\uFEFF',
    ].join('\r\n');
    const r = parseLibreViewCsv(`\uFEFF${tr}`, 'Europe/Istanbul');
    expect(r.readings.map((x) => [x.ts.toISOString(), x.mgdl])).toEqual([
      ['2026-09-25T20:45:00.000Z', 112],
      ['2026-09-25T21:00:00.000Z', 108],
    ]);
  });

  it('belirsiz tarih biçiminde zaman serisi tutarlılığı', () => {
    // 01-02 … 12-02: AA-GG ise ardışık aylar (tutarsız), GG-AA ise ardışık günler.
    const samples = Array.from(
      { length: 12 },
      (_, i) => `${String(i + 1).padStart(2, '0')}-02-2026 08:00`,
    );
    expect(detectDateFormat(samples)).toBe('DD-MM-YYYY HH:mm');
    expect(detectDateFormat(['garbage'])).toBeNull();
  });

  it('tanınmayan başlık', () => {
    expect(() => parseLibreViewCsv('a,b,c\n1,2,3', 'UTC')).toThrow(/başlığı/);
  });
});
